

INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Botas de pelusa','ninos','botas',19.99,'Botas cómodas y confortables.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/1/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/1/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/1/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/1/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Botín','ninos','botas',25.99,'Botines de cuero negro.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/2/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/2/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/2/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/2/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Botas cordones','ninos','botas',27.99,'Botas beige con cordones.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/3/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/3/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/3/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/3/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Botas','ninos','botas',30.00,'Botas negras con hebillas.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/4/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/4/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/4/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/4/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Bota multicolor','ninos','botas',17.99,'Botas con cordones multicolor.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/5/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/5/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/5/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/5/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Bota de agua','ninos','botas',19.99,'Botas de agua disney.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/6/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/6/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/6/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/6/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Botas Daysi','ninos','botas',28.99,'Botas con cordones disney');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/7/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/7/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/7/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninas/7/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Botín','ninos','botas',24.99,'Botín negro.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/1/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/1/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/1/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/1/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Bota de agua','ninos','botas',19.99,'Botas de agua Spiderman.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/2/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/2/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/2/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/2/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Botín','ninos','botas',30.00,'Botín marrón de montaña.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/3/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/3/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/3/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/3/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Botín','ninos','botas',30.00,'Botín negro con cordones.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/4/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/4/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/4/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/4/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Botín','ninos','botas',26.99,'Botín de color marrón confortable.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/5/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/5/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/5/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/5/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Bota engomada','ninos','botas',24.99,'Botas engomadas, para lluvia.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/6/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/6/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/6/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/6/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Botas','ninos','botas',35.99,'Botas clásicas marrones con hebillas.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/7/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/7/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/7/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/botas/ninos/7/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Deportivas Frozen','ninos','deportivas',24.99,'Deportivas Disney Elsa.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/1/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/1/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/1/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/1/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('RapidRunKids','ninos','deportivas',15.00,'Deportivas básicas, suela antideslizante y transpirables.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/2/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/2/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/2/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/2/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Deportivas Minnie','ninos','deportivas',17.99,'Deportivas Disney Minnie Mousse.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/3/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/3/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/3/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/3/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('TurboTrek','ninos','deportivas',17.99,'Deportivas cómodas antideslizante.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/4/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/4/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/4/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/4/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Deportiva multicolor','ninos','deportivas',20.99,'Deportivas running.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/5/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/5/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/5/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/5/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Deportivas','ninos','deportivas',15.99,'Deportivas básicas con cordones y plantilla efecto memoria.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/6/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/6/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/6/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/6/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Running','ninos','deportivas',16.99,'Deportivas básicas, cómodas con suela antideslizante.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/7/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/7/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninas/7/3.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Deportiva','ninos','deportivas',15.99,'Deportivas sin cordones, suaves y antideslizante.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/1/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/1/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/1/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/1/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Deportivas','ninos','deportivas',15.99,'Deportivas sin cordones,suaves y antideslizantes.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/2/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/2/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/2/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/2/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Pato Donald','ninos','deportivas',20.00,'Deportivas Disney de Pato Donald con cordones.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/3/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/3/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/3/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/3/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('YellowRun','ninos','deportivas',16.95,'Deportivas running confortables con plantilla efecto memoria.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/4/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/4/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/4/3.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Deportivas','ninos','deportivas',15.99,'Deportivas básicas, cómodas con suelo antideslizante.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/5/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/5/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/5/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/5/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Deportiva','ninos','deportivas',16.50,'Deportivas cómodas, de color negro, con velcro y cordones.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/6/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/6/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/6/3.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('GreenFast','ninos','deportivas',15.00,'Deportivas básicas, cómodas con suelo antideslizante.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/7/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/7/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/deportivas/ninos/7/3.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Piolín','ninos','zapatillas',25.99,'Zapatillas suaves de Piolín con cordones.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/1/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/1/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/1/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/1/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Zapatillas ','ninos','zapatillas',20.00,'Zapatillas de estrella feliz.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/2/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/2/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/2/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/2/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Zapatillas','ninos','zapatillas',30.00,'Zapatillas de doble suela.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/3/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/3/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/3/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/3/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Bamba','ninos','zapatillas',21.50,'Zapatillas de bamba, suaves y cómodas.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/4/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/4/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/4/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/4/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Pink','ninos','zapatillas',13.50,'Zapatillas cómodas con velcro.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/5/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/5/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/5/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/5/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Barbie','ninos','zapatillas',20.00,'Zapatillas de color rosa Barbie.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/6/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/6/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/6/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/6/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Stitch','ninos','zapatillas',20.00,'Zapatillas de Stitch con velcro, suela cómoda.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/7/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/7/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/7/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninas/7/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Zapatillas','ninos','zapatillas',30.00,'Zapatillas con doble suela.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/1/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/1/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/1/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/1/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Zapatillas','ninos','zapatillas',30.00,'Zapatillas de color marrón con plantilla flexible. ');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/2/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/2/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/2/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/2/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('White','ninos','zapatillas',25.99,'Zapatillas blancas clásicas con doble suela.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/3/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/3/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/3/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/3/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Zapatillas','ninos','zapatillas',20.00,'Zapatillas de color marrón con cordones.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/4/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/4/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/4/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/4/4.webp'));
INSERT INTO PRODUCTO (nombre, categoria,subcategoria,precio_ud,descripcion) values('Zapatillas','ninos','zapatillas',20.00,'Zapatillas con velcro y cordones de doble suela.');
SET @producto_id = LAST_INSERT_ID();
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/5/1.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/5/2.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/5/3.webp'));
INSERT INTO FOTOS (id_producto,foto) values (@producto_id,LOAD_FILE('C:/xampp/htdocs/Proyecto-grupal---Tienda-Online/assets/images/catalogo1/zapatillas_ninos/zapatillas/ninos/5/4.webp'));
